
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASS_SELECTOR COLON COMMA HEXCOLOR IDENTIFIER ID_SELECTOR LBRACE NUMBER RBRACE SEMICOLON UNITSstylesheet : rules\n| emptyrules : rule\n| rules rulerule : selector_list LBRACE declaration_list RBRACEselector : IDENTIFIER\n| ID_SELECTOR\n| CLASS_SELECTORselector_list : selector\n| selector_list COMMA selectordeclaration_list : declaration\n| declaration_list declaration\n| emptydeclaration : IDENTIFIER COLON value SEMICOLONvalue : IDENTIFIER\n| HEXCOLOR\n| NUMBER\n| NUMBER UNITSempty :'
    
_lr_action_items = {'$end':([0,1,2,3,4,10,18,],[-19,0,-1,-2,-3,-4,-5,]),'IDENTIFIER':([0,2,4,10,11,12,13,14,15,18,19,20,25,],[7,7,-3,-4,16,7,16,-11,-13,-5,-12,21,-14,]),'ID_SELECTOR':([0,2,4,10,12,18,],[8,8,-3,-4,8,-5,]),'CLASS_SELECTOR':([0,2,4,10,12,18,],[9,9,-3,-4,9,-5,]),'LBRACE':([5,6,7,8,9,17,],[11,-9,-6,-7,-8,-10,]),'COMMA':([5,6,7,8,9,17,],[12,-9,-6,-7,-8,-10,]),'RBRACE':([11,13,14,15,19,25,],[-19,18,-11,-13,-12,-14,]),'COLON':([16,],[20,]),'HEXCOLOR':([20,],[23,]),'NUMBER':([20,],[24,]),'SEMICOLON':([21,22,23,24,26,],[-15,25,-16,-17,-18,]),'UNITS':([24,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stylesheet':([0,],[1,]),'rules':([0,],[2,]),'empty':([0,11,],[3,15,]),'rule':([0,2,],[4,10,]),'selector_list':([0,2,],[5,5,]),'selector':([0,2,12,],[6,6,17,]),'declaration_list':([11,],[13,]),'declaration':([11,13,],[14,19,]),'value':([20,],[22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stylesheet","S'",1,None,None,None),
  ('stylesheet -> rules','stylesheet',1,'p_stylesheet','parser.py',13),
  ('stylesheet -> empty','stylesheet',1,'p_stylesheet','parser.py',14),
  ('rules -> rule','rules',1,'p_rules','parser.py',18),
  ('rules -> rules rule','rules',2,'p_rules','parser.py',19),
  ('rule -> selector_list LBRACE declaration_list RBRACE','rule',4,'p_rule','parser.py',23),
  ('selector -> IDENTIFIER','selector',1,'p_selector','parser.py',29),
  ('selector -> ID_SELECTOR','selector',1,'p_selector','parser.py',30),
  ('selector -> CLASS_SELECTOR','selector',1,'p_selector','parser.py',31),
  ('selector_list -> selector','selector_list',1,'p_selector_list','parser.py',35),
  ('selector_list -> selector_list COMMA selector','selector_list',3,'p_selector_list','parser.py',36),
  ('declaration_list -> declaration','declaration_list',1,'p_declaration_list','parser.py',40),
  ('declaration_list -> declaration_list declaration','declaration_list',2,'p_declaration_list','parser.py',41),
  ('declaration_list -> empty','declaration_list',1,'p_declaration_list','parser.py',42),
  ('declaration -> IDENTIFIER COLON value SEMICOLON','declaration',4,'p_declaration','parser.py',48),
  ('value -> IDENTIFIER','value',1,'p_value','parser.py',52),
  ('value -> HEXCOLOR','value',1,'p_value','parser.py',53),
  ('value -> NUMBER','value',1,'p_value','parser.py',54),
  ('value -> NUMBER UNITS','value',2,'p_value','parser.py',55),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',59),
]
